apiVersion: v1
kind: ConfigMap
metadata:
  name: capacity-update-trigger
  namespace: gpu-operator
data:
  update-capacity: |-
    version: v1
    flags:
      migStrategy: mixed
  update-capacity-1: |-
    version: v1
    flags:
      migStrategy: mixed
