apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: use-scc-instaslice-operator
subjects:
- kind: ServiceAccount
  name: instaslice-operator-controller-manager
  namespace: instaslice-system
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:instaslice-operator-scc
  apiGroup: rbac.authorization.k8s.io